config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users,path: '', path_names:{sign_in: 'login',sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except:[:show,:edit]  do
    put :sort, on: :collection
  end
  get 'tech_news', to: 'pages#tech_news'
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'
  get 'about-me', to: 'pages#about'     # get 'pages/about'
  get 'contact', to: 'pages#contact'# get 'pages/contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
   mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                          allow_destroy: true,
      reject_if: lambda{|attrs|attrs['name'].blank?}
  validates_presence_of :title, :body
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader
  def self.angular
    where(subtitle: "Angular")
  end
  def self.by_position
    order("position ASC")
  end
  scope :ruby, ->{where(subtitle: "Ruby On Rails")}
end

app/controllers/portfolios_controller.rb
#jhjjhjhj
class PortfoliosController < ApplicationController
   before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  def index
    @portfolio_items = Portfolio.by_position
  end
   def sort
     params[:order].each do |key, value|
       Portfolio.find(value[:id]).update(position: value[:position])
     end
     render nothing: true
   end
  def angular
    @angular_portfolio_items = Portfolio.angular
  end
  def new
    @portfolio_item = Portfolio.new
    # 3.times {@portfolio_item.technologies.build}
  end
  def create
    @portfolio_item = Portfolio.new((portfolio_params))
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Your Portfolio item is now live.' }
       format.json { render :show, status: :created, location: @portfolio_item }
      else
        format.html { render :new }
       format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
      end
    end
end

  def edit
  end
  def update
  respond_to do |format|
    if @portfolio_item.update((portfolio_params))
      format.html { redirect_to portfolios_path, notice: 'portfolio item was successfully updated.' }
      format.json { render :show, status: :ok, location: @portfolio_item }
    else
      format.html { render :edit }
      format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
    end
  end
  end
  def show
  end
  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
  def set_portfolio
     @portfolio_item = Portfolio.find(params[:id])
  end
  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :thumb_image,
                                      :main_image,
                                      technologies_attributes: [:id,:name,:_destroy])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:,width:)
    "http://placehold.it/#{height}x#{width}"
  end
  def porfolio_img img, type
    if img
      img
    else if type == 'thumb'
      image_generator(height: '350', width: '200')
    else if type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
    end
  end
  end
#self.main_image ||= Placeholder.image_generator(height: 600,width: 400)
#self.thumb_image ||=Placeholder.image_generator(height: 350,width: 200)

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>
  <div class="row">
   <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title,class:'form-control' %>
   </div>
    <div class="form-group">
      <%= form.label :subtitle %>
      <%= form.text_field :subtitle,class:'form-control' %>
    </div>
     <div class="form-group">
       <label class="btn btn-primary">
         Upload a main image file <%= form.file_field :main_image, style: 'display:none;' %>
       </label>
     </div>
     <div class="form-group">
       <label class="btn btn-primary">
         Upload a thumb image file <%= form.file_field :thumb_image, style: 'display:none;' %>
       </label>
     </div>
      </div>
    <div class="col-md-6">
        <div class="form-group">
          <%= form.label :body %>
              <%= form.text_area :body,class:'form-control',rows: 13 %>
        </div>
      </div>
    <div class="col-md-12">
    <h3>Technologies Used</h3>
    <div>
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields',f:technology_form %>
        <% end %>
      <div>
        <%= link_to_add_association 'Add Technologies',form ,:technologies %>
      </div>
      </div>
      <div class="form-group">
        <%= form.submit 'Save portfolio ',class: 'btn btn-primary btn-block' %>
      </div> 
    </div>
  </div>
<% end %>
    
 

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" data-id="<%= portfolio_item.id %>">
	<div class="card mb-4 shadow-sm">
	 <%= image_tag porfolio_img(portfolio_item.thumb_image_url,'thumb'), width: '100%' %>
		<div class="card-body">
		  <p class="card-text"> <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></span><%= portfolio_item.subtitle %></p>
		  <div class="d-flex justify-content-between align-items-center">
		    <div class="btn-group">
		      <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'view', portfolio_show_path(portfolio_item.id) %></button>
		      <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to 'edit', edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %></button>
		    </div>
		    <small class="text-muted">9 mins</small>
			</div>
		</div>
	</div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name,class:'form-control' %>
  <%= link_to_remove_association 'Remove Technology',f %>
</div>

app/views/portfolios/angular.html.erb
<h1> Angular Portfolio Items</h1>
<p><%= link_to "Create New Item", new_portfolio_url %></p>
<% @angular_portfolio_items.each do |portfolio_item| %>
  <p> <%= link_to portfolio_item.title, portfolio_show_path(portfolio_item.id) %></p>
  <p> <%= portfolio_item.subtitle %></p>
  <p> <%= portfolio_item.body %></p>
  <p> <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to "Show", portfolio_show_path(portfolio_item.id) %>
    <%= link_to "Edit portfolio_item", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
    <%= link_to 'Delete Portfolio Item', portfolio_show_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
  </p>
<% end %>

app/views/portfolios/edit.html.erb
<div class="container">
<h1> Edit this Portfolio Item </h1>
<%=render 'form',portfolio_item:@portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
    <div class="container">
      <%= source_helper("alert alert-warning")%>
  		<div class="row sortable">
			<%= render partial: 'portfolio_item', collection: @portfolio_items %> 
		</div>
	</div>
</div>

			
<!-- <p>< link_to "Create New Item", new_portfolio_url %></p>
 < render partial: 'portfolio_item', collection: @portfolio_items %>  -->

app/views/portfolios/new.html.erb
<div class="container">
	<h1> Create new Portfolio Item </h1>
	<%=render 'form',portfolio_item:@portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag porfolio_img(@portfolio_item.main_image_url,'main') %>
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>
			<em><%= @portfolio_item.subtitle %></em>
			<p><%= @portfolio_item.body %></p>
			<h2>Technologies Used</h2>
			<% @portfolio_item.technologies.each do |t| %>
			<p><%= t.name %></p>
			<% end %>
      <% if logged_in?(:site_admin) %>
      <div class="col-md-12">
        <%= link_to "Edit Item",edit_portfolio_path(@portfolio_item),class: 'btn btn-warning' %>
      </div>
      <% end %>
		</div>
	</div>
</div>