config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users,path: '', path_names:{sign_in: 'login',sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except:[:show,:edit]  do
    put :sort, on: :collection
  end
  get 'tech_news', to: 'pages#tech_news'
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'
  get 'about-me', to: 'pages#about'     # get 'pages/about'
  get 'contact', to: 'pages#contact'# get 'pages/contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
   mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p class="app-footer">   <%= copyright_generator %> </p>
  </div>
</footer>
</div>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Jordan Hudgens</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= nav_helper 'nav-link','span' %>
      <%= login_helper 'nav-link active?' %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
   <%= render "shared/application_footer"%>
    <p><a href="#">Back to top</a></p>
</footer>

app/views/shared/_blog_masthead_fir.html.erb
<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">My blog</h1>
    <p class="lead my-3">Multiple lines of text that form the lede, informing new readers quickly and efficiently about what’s most interesting in this post’s contents.</p>
    <p class="lead mb-0"><a href="#" class="text-white font-weight-bold">Continue reading...</a></p>
  </div>
</div>

app/views/shared/_blog_masthead_sec.html.erb
<div class="row mb-2">
  <div class="col-md-6">
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-primary">World</strong>
        <h3 class="mb-0">Featured post</h3>
        <div class="mb-1 text-muted">Nov 12</div>
        <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="stretched-link">Continue reading</a>
      </div>
      <div class="col-auto d-none d-lg-block">
        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <strong class="d-inline-block mb-2 text-success">Design</strong>
        <h3 class="mb-0">Post title</h3>
        <div class="mb-1 text-muted">Nov 11</div>
        <p class="mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
        <a href="#" class="stretched-link">Continue reading</a>
      </div>
      <div class="col-auto d-none d-lg-block">
        <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
      </div>
    </div>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light blog-nav">
  <%= link_to "Tekleab B.", root_path, class: 'navbar-brand'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <%= nav_helper 'nav-link','li'%>
      <%= login_helper 'nav-link' %>
    </ul>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
                      <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="font-italic">About</h4>
                        <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
                      </div>
                        <%= source_helper("alert alert-info")%>
                      <div class="p-4">
                        <h4>Topics</h4>
                        <% @side_bar_topics.each do |topic| %>
                        <p><%= link_to topic.title, topic_path(topic) %></p>
                        <% end %>
                      </div>
                      <div class="p-4">
                        <h4 class="font-italic">Elsewhere</h4>
                        <ol class="list-unstyled social-links">
                          <li><a href="#"><%= fa_icon "github" %></a></li>
                          <li><a href="#"><%= fa_icon "twitter", base: "square-o" %></a></li>
                          <li><a href="#"><%= fa_icon "instagram" %></a></li>
                          <li><a href="#"><%= fa_icon "facebook" %></a></li>
                        </ol>
                      </div>
                    </aside><!-- /.blog-sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home",root_path %></div>
  <div><%= link_to "About",about_me_path %></div>
  <div><%= link_to "Contact",contact_path %></div>
  <div><%= link_to "Blog",blogs_path %></div>
  <div><%= link_to "Portfolio",portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>/<%= link_to 'Show all Portfolios',portfolios_path %>
    </p>
   <%= copyright_generator %>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
      <h1>Album Example</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
      <%= link_to 'Find Out More About Me', about_me_path,class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path,class: 'btn btn-secondary' %>
      </p>
    </div>
  </section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            
            <%= nav_helper 'text-white','li' %>
            <li><%= login_helper 'text-white active?' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="mr-2" viewBox="0 0 24 24" focusable="false"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>fam@teck</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>