config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users,path: '', path_names:{sign_in: 'login',sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except:[:show,:edit]  do
    put :sort, on: :collection
  end
  get 'tech_news', to: 'pages#tech_news'
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  get 'portfolio/:id/edit', to: 'portfolios#edit', as: 'edit_portfolio'
  get 'about-me', to: 'pages#about'     # get 'pages/about'
  get 'contact', to: 'pages#contact'# get 'pages/contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
   mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content = <%= @seo_keywords %>>
    <%= favicon_link_tag 'favicons/favicon.ico' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <div id="background"></div>
    <%= render "shared/application_nav"%>

    <%= yield %>
    <%= alerts %>
    <%= render "shared/application_footer"%>
  </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
  <html>
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content = <%= @seo_keywords %>>
      <%= favicon_link_tag 'favicons/favicon3.ico' %>
    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <div class="container">
                <%= render 'shared/blog_nav' %>
                <%= render 'shared/blog_masthead_fir' unless logged_in?(:site_admin) %>
                <%= render 'shared/blog_masthead_sec' unless logged_in?(:site_admin) %>

        <span><%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %></span>
        <span><%= link_to "Topics", topics_path %></span>
                
                   </div>  
                  <!-- <hr> -->
                   <main role="main" class="container">
                   <div class="row">

                    <%= yield %>
                     <%= alerts %>
                    <%= render 'shared/blog_sidebar' %>
                  <!-- < render "shared/nav",location: 'bottom' %> -->
                  <div>
                 
                </div>
                    </div>
                </main>
                <%= render '/shared/blog_footer' %>

    </body>
  </html>

app/views/layouts/portfolio.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="keywords" content = <%= @seo_keywords %>>
    <%= favicon_link_tag 'favicons/favicon2.ico' %>
    <%= stylesheet_link_tag    'portfolios', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
<%= render 'shared/portfolio_nav' %> 
  <%=render 'shared/portfolio_masthead' unless logged_in?(:site_admin) %>
    <%= yield %>
<%= alerts %>
<hr>
<%= render 'shared/portfolio_footer' %>
  </body>
</html>